version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase...
      - npm build
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
