version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - rm -rf /var/www/html/*
      - npm install
  build:
    commands:
      - echo Build phase...
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
