version: 0.2
cache:
  paths:
    - /root/.cache/npm/**/*
  override: true
phases:
  prebuild:
    commands:
      - rm -rf node_modules
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase...
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
