version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm cache clean --force
      - npm install
  build:
    commands:
      - echo Build phase...
  post_build:
    commands:
      - echo Build completed successfully.
#cache:
#  path:
#    - 
#  override: true
artifacts:
  files:
    - '**/*'
